blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/tags/c/sdks/5/swift
    about: Ask general support or usage questions in the Auth0 Community forums
