coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - Auth0Tests/*
  status:
    patch:
      default:
        if_no_uploads: error
    changes: true
    project:
      default:
        target: auto
        if_no_uploads: error
comment:
  layout: "header, diff, changes, uncovered"
  behavior: default